# Generated by Django 3.1.5 on 2021-03-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
