# Generated by Django 3.1.5 on 2021-03-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210306_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AlterField(
            model_name='todo',
            name='pdf',
            field=models.FileField(upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
